### ISSUE TITLE
Script NGinn database

### ISSUE THREAD

**Issue by Sorcerys** [lafar6502/nginn-messagebus#2]
Is possible attach the database scripts (database, tables,views,...) into de source ?

thanks

**Comment by lafar6502** [comment]
SQL scripts are included in sources as embedded resources - please check the NGinnBPM.MessageBus project. The problem is they're just SQL templates used for creating DB structure at runtime (the db structure is not static - each queue has its own table etc so you'll have to compile your own db creation script from these). 
Anyway, it's not necessary to create the db structure upfront, if your db user has sufficient rights the structure will be created automatically on startup.
